"""Curated operation catalogue derived from the documented firmware surface."""

from __future__ import annotations

from typing import TYPE_CHECKING, TypeAlias

from .endpoint_spec import EndpointSpec

if TYPE_CHECKING:
    from ._json import JsonObject
    from .endpoint_spec import AuthenticationMode, ResponseKind, SafetyLevel, SensitivityLevel

CATALOG_VERSION = 4
P9_PROFILE_FIRMWARE = "1.3.0 Build 20250804 Rel. 58832"
P9_PROFILE_HARDWARE_VERSIONS: tuple[str, ...] = ("1.0", "2.0")
P9_PROFILE_OBSERVED_AT = "2026-07-11T08:40:28Z"

_DOCUMENTATION: dict[str, str] = {
    "login": "docs/endpoints/login.md",
    "domain_login": "docs/endpoints/login.md",
    "admin/network": "docs/endpoints/network.md",
    "admin/route": "docs/endpoints/routing.md",
    "admin/dhcp": "docs/endpoints/dhcp.md",
    "admin/wireless": "docs/endpoints/wireless.md",
    "admin/network_optimize": "docs/endpoints/wireless.md",
    "admin/device": "docs/endpoints/device.md",
    "admin/system": "docs/endpoints/system.md",
    "admin/component_control": "docs/endpoints/system.md",
    "admin/web": "docs/endpoints/system.md",
    "locale": "docs/endpoints/system.md",
    "admin/eco_mode": "docs/endpoints/eco-mode-and-time.md",
    "admin/time_setting": "docs/endpoints/eco-mode-and-time.md",
    "admin/client": "docs/endpoints/clients.md",
    "admin/nrd": "docs/endpoints/clients.md",
    "admin/smart_network": "docs/endpoints/parental-control-and-qos.md",
    "admin/security": "docs/endpoints/homeshield-security.md",
    "admin/camera_security": "docs/endpoints/homeshield-security.md",
    "admin/firmware": "docs/endpoints/firmware-and-upgrade.md",
    "admin/isp": "docs/endpoints/firmware-and-upgrade.md",
    "mcu_upgrade": "docs/endpoints/firmware-and-upgrade.md",
    "admin/cloud": "docs/endpoints/cloud-and-account.md",
    "admin/cloud_account": "docs/endpoints/cloud-and-account.md",
    "admin/iot_device": "docs/endpoints/iot-smart-home.md",
    "admin/iot_automation": "docs/endpoints/iot-smart-home.md",
    "admin/iot_cloud": "docs/endpoints/iot-smart-home.md",
    "admin/iot_client_mesh": "docs/endpoints/iot-smart-home.md",
    "admin/msg_server": "docs/endpoints/iot-smart-home.md",
    "admin/wps": "docs/endpoints/wps.md",
    "admin/wpsd": "docs/endpoints/wps.md",
    "admin/vpn_client": "docs/endpoints/vpn.md",
    "admin/vpn_server": "docs/endpoints/vpn.md",
    "admin/vpnconn": "docs/endpoints/vpn.md",
    "admin/nat": "docs/endpoints/nat-port-forwarding.md",
    "admin/ddns": "docs/endpoints/ddns.md",
    "admin/ipv6_firewall": "docs/endpoints/ipv6-firewall.md",
    "admin/iptv": "docs/endpoints/iptv.md",
    "admin/usbshare": "docs/endpoints/storage-usb.md",
    "admin/time_machine": "docs/endpoints/storage-usb.md",
    "admin/folder_sharing": "docs/endpoints/storage-usb.md",
    "admin/administration": "docs/endpoints/administration.md",
    "admin/quick_setup": "docs/endpoints/onboarding-and-provisioning.md",
    "admin/tipc-controller": "docs/endpoints/onboarding-and-provisioning.md",
    "discover": "docs/endpoints/onboarding-and-provisioning.md",
    "admin/sync": "docs/endpoints/onboarding-and-provisioning.md",
    "admin/log": "docs/endpoints/logs-and-diagnostics.md",
    "admin/log_export": "docs/endpoints/logs-and-diagnostics.md",
    "admin/syslog": "docs/endpoints/logs-and-diagnostics.md",
    "admin/telemetry_collect": "docs/endpoints/logs-and-diagnostics.md",
    "admin/debug": "docs/endpoints/logs-and-diagnostics.md",
    "admin/auto_test": "docs/endpoints/logs-and-diagnostics.md",
    "admin/arptbl": "docs/endpoints/logs-and-diagnostics.md",
    "admin/cwmp": "docs/endpoints/misc-services.md",
    "admin/combo_port": "docs/endpoints/misc-services.md",
    "admin/component_list": "docs/endpoints/misc-services.md",
    "admin/ga_info": "docs/endpoints/misc-services.md",
    "admin/op_manager": "docs/endpoints/misc-services.md",
    "blocking": "docs/endpoints/misc-services.md",
    "admin/wifidog": "docs/endpoints/misc-services.md",
    "admin/conn-indicator": "docs/endpoints/misc-services.md",
    "admin/re_disconnect_cloud": "docs/endpoints/misc-services.md",
}

_ParameterContract: TypeAlias = tuple[tuple[str, ...], tuple[str, ...]]
_PARAMETER_CONTRACTS: dict[tuple[str, str, str], _ParameterContract] = {
    ("admin/network", "wan_mode", "write"): (("mode",), ()),
    ("admin/network", "lan_ip", "write"): (("ip", "mask"), ("device_mac",)),
    ("admin/network", "dhcp_dial", "write"): (("enable_unicast",), ()),
    ("admin/network", "igmp_setting", "write"): (("enable_join_igmpv3",), ()),
    ("admin/network", "wifi_network", "write"): (("enable_wfnetwork",), ()),
    ("admin/network", "erp_setting", "write"): (
        (),
        ("enable_2g", "enable_5g", "enable_6g", "enable_dsl"),
    ),
    ("admin/network", "flow_control", "write"): (("enable_flow_control",), ()),
    ("admin/network", "fast_xmit_setting", "write"): (("enable",), ()),
    ("admin/network", "flow_control_lan_wan", "write"): (
        (),
        ("wan_rx_enable", "wan_tx_enable", "lan_tx_enable", "lan_rx_enable"),
    ),
    ("admin/network", "vlan", "set_vlan"): (("vlan_id",), ("enable",)),
    ("admin/network", "vlan", "write"): (("vlan_id",), ("enable",)),
    ("admin/network", "mac_clone", "write"): (("clone_mode",), ("mac",)),
    ("admin/network", "routes_static", "add"): (
        ("name", "target", "netmask", "gateway", "interface"),
        ("enable",),
    ),
    ("admin/network", "routes_static", "modify"): (
        ("key", "name", "target", "netmask", "gateway", "interface"),
        ("enable",),
    ),
    ("admin/network", "routes_static", "remove"): (("key",), ()),
    ("admin/dhcp", "dhcp_info", "write"): (
        ("startIpAddress", "endIpAddress"),
        ("defaultGateway", "primaryDns", "secondaryDns"),
    ),
    ("admin/wireless", "ieee80211r", "write"): (("enable",), ()),
    ("admin/wireless", "beamforming", "write"): (("enable",), ()),
    ("admin/wireless", "operation_mode", "write"): (("mode",), ()),
    ("admin/wireless", "bandwidth_enhance", "write"): (("enable_ht160",), ()),
    ("admin/wireless", "ofdma", "write"): (("enable",), ("mode",)),
    ("admin/wireless", "power", "write"): (
        (),
        ("band2_4", "band5_1", "band5_2"),
    ),
    ("admin/device", "timesetting", "write"): (
        ("timezone", "continent", "tz_region"),
        (),
    ),
    ("admin/device", "system", "reboot"): (("mac_list",), ()),
    ("admin/device", "device_list", "remove"): (("device_id",), ()),
    ("admin/device", "reboot", "write"): (("device_id",), ()),
    ("admin/device", "system", "write"): (
        (),
        ("device_mac", "nickname", "custom_nickname"),
    ),
    ("admin/device", "led", "write"): (
        ("enable",),
        ("device_mac", "night_mode", "time_begin", "time_end"),
    ),
    ("locale", "lang", "write"): (("locale",), ()),
    ("locale", "country", "write"): (("value",), ()),
    ("admin/client", "client", "write"): (
        ("mac",),
        (
            "name",
            "client_type",
            "enable_priority",
            "remain_time",
            "owner_id",
            "space_id",
        ),
    ),
    ("admin/client", "client_access", "write"): (("mac", "action"), ()),
    ("admin/client", "black_list", "add"): (("mac",), ("name", "client_type")),
    ("admin/client", "black_list", "remove"): (("mac",), ()),
    ("admin/client", "block", "write"): (("mac",), ()),
    ("admin/client", "unblock", "write"): (("mac",), ()),
    ("admin/client", "addr_reservation", "add"): (("mac", "ip"), ()),
    ("admin/client", "addr_reservation", "modify"): (("mac", "ip"), ("old_mac",)),
    ("admin/client", "addr_reservation", "remove"): (("mac",), ("ip",)),
    ("admin/smart_network", "bandwidth", "set"): (
        ("upstream_bandwidth", "downstream_bandwidth"),
        (),
    ),
    ("admin/nat", "vs", "add"): (
        ("name", "external_port", "internal_ip", "internal_port", "protocol"),
        ("enable",),
    ),
    ("admin/nat", "vs", "modify"): (
        ("port_forwarding_id",),
        ("name", "external_port", "internal_ip", "internal_port", "protocol", "enable"),
    ),
    ("admin/nat", "vs", "remove"): (("port_forwarding_id",), ()),
    ("admin/nat", "dmz", "write"): (("enable",), ("ipaddr",)),
    ("admin/nat", "sip_alg", "set"): (("enable",), ()),
    ("admin/ddns", "ddns", "set"): (
        ("ddns_status",),
        ("mode", "provider", "domain_name", "username", "password", "update_interval"),
    ),
    ("admin/ipv6_firewall", "firewall", "remove"): (("id",), ()),
    ("admin/iptv", "iptv", "set"): (
        ("enable",),
        ("mode", "type", "vlan_id", "vlan_priority", "isp_name", "tag_802_1q"),
    ),
    ("admin/wps", "state", "set"): (("state",), ("dev",)),
    ("admin/cloud", "firmware", "upload"): (
        ("hw_id", "oem_id", "device_model"),
        (),
    ),
    ("admin/syslog", "mail", "write"): (
        ("from", "password", "smtp_server", "port", "to"),
        ("auth", "auto_mail", "auto_mail_type", "every_day_time", "every_hours", "mail_again"),
    ),
    ("admin/cwmp", "cwmp_info", "write"): (
        (),
        (
            "cwmp_enable",
            "inform_enable",
            "inform_interval",
            "ACS_URL",
            "ACS_Username",
            "ACS_Password",
            "Connection_Auth",
            "Username",
            "Password",
            "Path",
            "Port",
            "STUNEnable",
            "MaxKeepPeriod",
            "MinKeepPeriod",
            "STUNSAdd",
            "STUNSPort",
            "STUNUsername",
            "STUNPassword",
        ),
    ),
}

_FIRMWARE_ASSET_CONTRACTS: frozenset[tuple[str, str, str]] = frozenset(
    {
        ("admin/network", "dhcp_dial", "write"),
        ("admin/network", "igmp_setting", "write"),
        ("admin/network", "wifi_network", "write"),
        ("admin/network", "erp_setting", "write"),
        ("admin/network", "flow_control", "write"),
        ("admin/network", "fast_xmit_setting", "write"),
        ("admin/network", "flow_control_lan_wan", "write"),
        ("admin/wireless", "power", "write"),
        ("admin/device", "timesetting", "write"),
        ("admin/device", "system", "reboot"),
        ("admin/cloud", "firmware", "upload"),
        ("admin/firmware", "config_multipart", "backup"),
        ("admin/syslog", "mail", "write"),
        ("admin/cwmp", "cwmp_info", "write"),
    }
)


def _specs(
    path: str,
    form: str,
    operations: tuple[str, ...],
    *,
    authentication: AuthenticationMode = "encrypted",
    response_kind: ResponseKind = "object",
    safety: SafetyLevel = "read_only",
    sensitivity: SensitivityLevel = "normal",
    default_params: JsonObject | None = None,
    media_type: str = "application/json",
    form_selector: bool = True,
) -> tuple[EndpointSpec, ...]:
    endpoint_specs: list[EndpointSpec] = []
    for operation in operations:
        contract_key = (path, form, operation)
        required_params, optional_params = _PARAMETER_CONTRACTS.get(
            contract_key,
            ((), ()),
        )
        endpoint_specs.append(
            EndpointSpec(
                path=path,
                form=form,
                operation=operation,
                authentication=authentication,
                response_kind=response_kind,
                safety=safety,
                sensitivity=sensitivity,
                default_params=default_params,
                documentation=_DOCUMENTATION.get(path, "docs/endpoints/README.md"),
                media_type=media_type,
                required_params=required_params,
                optional_params=optional_params,
                contract_source=(
                    "firmware_asset"
                    if contract_key in _FIRMWARE_ASSET_CONTRACTS
                    else "documented"
                    if required_params or optional_params
                    else "none"
                ),
                form_selector=form_selector,
            )
        )
    return tuple(endpoint_specs)


ENDPOINT_CATALOG: tuple[EndpointSpec, ...] = (
    *_specs("login", "auth", ("read",), authentication="bootstrap"),
    *_specs("login", "keys", ("read",), authentication="bootstrap"),
    *_specs(
        "login",
        "login",
        ("login",),
        authentication="bootstrap",
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("login", "check_factory_default", ("read",), authentication="bootstrap"),
    *_specs(
        "login",
        "default_info",
        ("read",),
        authentication="bootstrap",
        sensitivity="secret",
    ),
    *_specs(
        "login",
        "mini_login",
        ("login",),
        authentication="bootstrap",
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "login",
        "cloud_login",
        ("login",),
        authentication="bootstrap",
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "domain_login",
        "dlogin",
        ("read",),
        authentication="encrypted",
        sensitivity="secret",
    ),
    *_specs(
        "domain_login",
        "dlogin",
        ("write",),
        authentication="encrypted",
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/network", "wan_mode", ("read",)),
    *_specs("admin/network", "wan_mode", ("write",), safety="mutation"),
    *_specs(
        "admin/network",
        "wan_ipv4",
        ("read",),
        sensitivity="secret",
        default_params={"device_mac": "default"},
    ),
    *_specs(
        "admin/network",
        "wan_ipv4",
        ("write", "connect", "disconnect"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/network",
        "lan_ipv4",
        ("read",),
        sensitivity="private",
        default_params={"device_mac": "default"},
    ),
    *_specs(
        "admin/network",
        "lan_ip",
        ("read",),
        sensitivity="private",
        default_params={"device_mac": "default"},
    ),
    *_specs("admin/network", "lan_ip", ("write",), safety="mutation", sensitivity="private"),
    *_specs("admin/network", "lan_block", ("read",), sensitivity="private"),
    *_specs("admin/network", "lan_block", ("write",), safety="mutation"),
    *_specs("admin/network", "internet", ("read",), sensitivity="private"),
    *_specs("admin/network", "ipv6", ("read",), sensitivity="secret"),
    *_specs("admin/network", "ipv6", ("write",), safety="mutation", sensitivity="private"),
    *_specs("admin/network", "vlan", ("read", "get_vlan")),
    *_specs("admin/network", "vlan", ("write", "set_vlan"), safety="mutation"),
    *_specs("admin/network", "mac_clone", ("read",), sensitivity="private"),
    *_specs("admin/network", "mac_clone", ("write",), safety="mutation"),
    *_specs("admin/network", "mac_clone_list", ("read",), sensitivity="private"),
    *_specs("admin/network", "performance", ("read",)),
    *_specs("admin/network", "dhcp_dial", ("read",), sensitivity="secret"),
    *_specs("admin/network", "dhcp_dial", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/network", "igmp_setting", ("read",)),
    *_specs("admin/network", "igmp_setting", ("write",), safety="mutation"),
    *_specs("admin/network", "wifi_network", ("read",), sensitivity="private"),
    *_specs("admin/network", "wifi_network", ("write",), safety="mutation"),
    *_specs("admin/network", "erp_setting", ("read",)),
    *_specs("admin/network", "erp_setting", ("write",), safety="mutation"),
    *_specs("admin/network", "flow_control", ("read",)),
    *_specs("admin/network", "flow_control", ("write",), safety="mutation"),
    *_specs("admin/network", "fast_xmit_setting", ("read",)),
    *_specs("admin/network", "fast_xmit_setting", ("write",), safety="mutation"),
    *_specs("admin/network", "flow_control_lan_wan", ("read",)),
    *_specs("admin/network", "flow_control_lan_wan", ("write",), safety="mutation"),
    *_specs("admin/network", "upnp", ("read",), sensitivity="private"),
    *_specs("admin/network", "upnp", ("write",), safety="mutation"),
    *_specs("admin/network", "routes_static", ("getlist",), sensitivity="private"),
    *_specs(
        "admin/network",
        "routes_static",
        ("add", "modify", "remove"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/network", "routes_system", ("getlist",), sensitivity="private"),
    *_specs(
        "admin/network",
        "dsl_status",
        ("read",),
        default_params={"device_mac": "default"},
    ),
    *_specs(
        "admin/route",
        "route",
        ("read",),
        sensitivity="private",
        form_selector=False,
    ),
    *_specs(
        "admin/route",
        "route",
        ("insert", "delete", "update"),
        safety="mutation",
        sensitivity="private",
        form_selector=False,
    ),
    *_specs("admin/dhcp", "dhcp_info", ("read",), sensitivity="private"),
    *_specs("admin/dhcp", "dhcp_info", ("write",), safety="mutation", sensitivity="private"),
    *_specs("admin/dhcp", "dhcp_dial", ("set",), safety="mutation"),
    *_specs("admin/dhcp", "dhcp_ap", ("get",)),
    *_specs("admin/dhcp", "dhcp_ap", ("set",), safety="mutation"),
    *_specs("admin/wireless", "wlan", ("read",), sensitivity="secret"),
    *_specs("admin/wireless", "wlan", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/wireless", "operation_mode", ("read",)),
    *_specs("admin/wireless", "operation_mode", ("write",), safety="mutation"),
    *_specs(
        "admin/wireless",
        "bridge",
        ("read", "get_bridge_status"),
        sensitivity="private",
    ),
    *_specs("admin/wireless", "check", ("check",), sensitivity="private"),
    *_specs("admin/wireless", "ieee80211r", ("read",)),
    *_specs("admin/wireless", "ieee80211r", ("write",), safety="mutation"),
    *_specs("admin/wireless", "beamforming", ("read",)),
    *_specs("admin/wireless", "beamforming", ("write",), safety="mutation"),
    *_specs("admin/wireless", "bandwidth_enhance", ("read",)),
    *_specs("admin/wireless", "bandwidth_enhance", ("write",), safety="mutation"),
    *_specs("admin/wireless", "bandwidth_switch", ("read",)),
    *_specs("admin/wireless", "bandwidth_switch", ("write",), safety="mutation"),
    *_specs(
        "admin/wireless",
        "power",
        ("read",),
        default_params={"device_mac": "default"},
    ),
    *_specs("admin/wireless", "power", ("write",), safety="mutation"),
    *_specs("admin/wireless", "smart_antenna", ("read",)),
    *_specs("admin/wireless", "smart_antenna", ("write",), safety="mutation"),
    *_specs("admin/wireless", "wifi_schedule", ("read",)),
    *_specs("admin/wireless", "wifi_schedule", ("write",), safety="mutation"),
    *_specs("admin/wireless", "ofdma", ("read",)),
    *_specs("admin/wireless", "ofdma", ("write",), safety="mutation"),
    *_specs("admin/wireless", "mlo_network", ("read",), sensitivity="secret"),
    *_specs("admin/wireless", "mlo_network", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/wireless", "backhaul_optimization", ("read",)),
    *_specs("admin/wireless", "backhaul_optimization", ("write",), safety="mutation"),
    *_specs("admin/wireless", "get_support", ("read",)),
    *_specs("admin/network_optimize", "acs_optimize", ("read",)),
    *_specs("admin/network_optimize", "acs_optimize", ("write",), safety="mutation"),
    *_specs("admin/network_optimize", "acs_filter_macs", ("get",), sensitivity="private"),
    *_specs("admin/device", "device_list", ("read",), sensitivity="private"),
    *_specs("admin/device", "device_list", ("remove",), safety="destructive"),
    *_specs("admin/device", "mode", ("read",)),
    *_specs("admin/device", "speedtest", ("read",)),
    *_specs("admin/device", "speedtest", ("write", "stop"), safety="mutation"),
    *_specs("admin/device", "speedinfo", ("read",)),
    *_specs("admin/device", "timesetting", ("read",)),
    *_specs("admin/device", "timesetting", ("write",), safety="mutation"),
    *_specs("admin/device", "timesetting", ("gmt",), safety="mutation"),
    *_specs("admin/device", "system", ("read",), sensitivity="private"),
    *_specs("admin/device", "system", ("write",), safety="mutation"),
    *_specs("admin/device", "system", ("reboot",), safety="destructive"),
    *_specs("admin/device", "reboot", ("write",), safety="destructive"),
    *_specs("admin/device", "factory", ("write",), safety="destructive"),
    *_specs("admin/device", "gateway", ("read",)),
    *_specs("admin/device", "mini_device_list", ("read",), sensitivity="private"),
    *_specs("admin/device", "envar", ("read",)),
    *_specs("admin/device", "envar", ("write",), safety="mutation"),
    *_specs("admin/device", "get_server", ("read",)),
    *_specs("admin/device", "get_server", ("clear",), safety="mutation"),
    *_specs("admin/device", "led", ("read",)),
    *_specs("admin/device", "led", ("write",), safety="mutation"),
    *_specs("admin/device", "sysmode", ("read",)),
    *_specs("admin/device", "set_backup", ("write",), safety="mutation"),
    *_specs("admin/device", "device_prefer_set", ("set",), safety="mutation"),
    *_specs("admin/device", "signal_level_list", ("read",), sensitivity="private"),
    *_specs("admin/device", "detect_mode", ("read",)),
    *_specs("admin/device", "fixed_wan_port", ("read",)),
    *_specs("admin/device", "fixed_wan_port", ("write",), safety="mutation"),
    *_specs("admin/device", "systime", ("read",)),
    *_specs("admin/device", "eco_mode", ("read",)),
    *_specs("admin/device", "eco_mode", ("write",), safety="mutation"),
    *_specs("admin/system", "envar", ("read",), authentication="plain"),
    *_specs("admin/system", "envar", ("write",), authentication="plain", safety="mutation"),
    *_specs("admin/system", "sysmode", ("read",), authentication="plain"),
    *_specs("admin/system", "logout", ("write",), safety="mutation"),
    *_specs("admin/system", "logout", ("logout",), safety="mutation"),
    *_specs("admin/component_control", "switch_list", ("read",)),
    *_specs("admin/web", "extra_component_info", ("get",)),
    *_specs("locale", "lang", ("read",)),
    *_specs("locale", "lang", ("write",), safety="mutation"),
    *_specs("locale", "country", ("read",)),
    *_specs("locale", "country", ("write",), safety="mutation"),
    *_specs("locale", "country_list", ("read",)),
    *_specs("locale", "list", ("read",), response_kind="list"),
    *_specs("admin/eco_mode", "eco_mode", ("read",)),
    *_specs("admin/eco_mode", "eco_mode", ("write",), safety="mutation"),
    *_specs("admin/eco_mode", "get_period", ("read",)),
    *_specs("admin/eco_mode", "skip_schedule", ("write",), safety="mutation"),
    *_specs("admin/time_setting", "request", ("read",)),
    *_specs("admin/time_setting", "notify", ("write",), safety="mutation"),
    *_specs(
        "admin/client",
        "client_list",
        ("read",),
        sensitivity="private",
        default_params={"device_mac": "default"},
    ),
    *_specs("admin/client", "client", ("read",), sensitivity="private"),
    *_specs("admin/client", "client", ("write",), safety="mutation", sensitivity="private"),
    *_specs("admin/client", "traffic_stat", ("read", "list"), sensitivity="private"),
    *_specs("admin/client", "black_list", ("getlist", "list"), sensitivity="private"),
    *_specs(
        "admin/client",
        "black_list",
        ("add", "remove"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/client", "block", ("write",), safety="mutation", sensitivity="private"),
    *_specs("admin/client", "unblock", ("write",), safety="mutation", sensitivity="private"),
    *_specs("admin/client", "addr_reservation", ("getlist",), sensitivity="private"),
    *_specs(
        "admin/client",
        "addr_reservation",
        ("add", "modify", "remove"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/client", "client_access", ("write",), safety="mutation"),
    *_specs("admin/client", "client_isolation", ("read",)),
    *_specs("admin/client", "client_isolation", ("write",), safety="mutation"),
    *_specs("admin/client", "access_refuse", ("get",), sensitivity="private"),
    *_specs(
        "admin/client",
        "access_refuse",
        ("write",),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/client", "apply_list", ("get",), sensitivity="private"),
    *_specs("admin/client", "apply_list", ("set",), safety="mutation", sensitivity="private"),
    *_specs("admin/client", "white_list", ("get",), sensitivity="private"),
    *_specs("admin/client", "lease", ("get",), sensitivity="private"),
    *_specs("admin/nrd", "black_list", ("list",), sensitivity="private"),
    *_specs(
        "admin/nrd",
        "black_list",
        ("block", "unblock"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/smart_network", "tm_qos", ("read",)),
    *_specs("admin/smart_network", "tm_qos", ("write",), safety="mutation"),
    *_specs("admin/smart_network", "bandwidth", ("get",)),
    *_specs("admin/smart_network", "bandwidth", ("set",), safety="mutation"),
    *_specs("admin/smart_network", "patrol_owner", ("list", "get"), sensitivity="private"),
    *_specs(
        "admin/smart_network",
        "patrol_owner",
        ("add", "del", "block", "set"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "patrol_insights",
        ("get", "history"),
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "patrol_insights",
        ("remove",),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "patrol_cli",
        ("add", "del"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/smart_network", "patrol_filter", ("get",), sensitivity="private"),
    *_specs(
        "admin/smart_network",
        "patrol_filter",
        ("add", "del"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "patrol_owner_avatar",
        ("get",),
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "patrol_owner_avatar",
        ("set",),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/smart_network", "white_list", ("get",), sensitivity="private"),
    *_specs(
        "admin/smart_network",
        "white_list",
        ("add", "remove"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/smart_network", "app_block_list", ("read",), sensitivity="private"),
    *_specs(
        "admin/smart_network",
        "app_dpi",
        ("add", "modify", "remove"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "time_limit_add",
        ("write",),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "time_limit_modify",
        ("write",),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "time_limit_remove",
        ("write",),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/smart_network",
        "tmp_avira",
        (
            "getOwnerInList",
            "getFamilyTimeInfo",
            "getTodayInsightTimeUsagePro",
            "getInsightData",
            "scanGet",
            "ispGet",
            "service_state_check",
            "service_status_check",
            "cloud_service_state_check",
            "get_sec_whitelist",
        ),
        sensitivity="secret",
    ),
    *_specs(
        "admin/smart_network",
        "tmp_avira",
        (
            "addOwnerInList",
            "delOwnerInList",
            "modifyBaseInfo",
            "bonusTimeSet",
            "ownerClientListSet",
            "white_list_add",
            "white_list_remove",
            "setFamilyTimeInfo",
            "ignoreReq",
            "scanStart",
            "scanStop",
            "networkQualityStartOptimize",
            "add_sec_whitelist",
            "remove_sec_whitelist",
        ),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/security", "info", ("read",), sensitivity="private"),
    *_specs("admin/security", "info", ("write",), safety="mutation"),
    *_specs("admin/security", "category", ("read",)),
    *_specs("admin/security", "rule", ("read",)),
    *_specs("admin/security", "history", ("get",), sensitivity="private"),
    *_specs(
        "admin/security",
        "history",
        ("clear", "remove"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/security", "update", ("write",), safety="mutation"),
    *_specs("admin/camera_security", "camera_security", ("get",), sensitivity="private"),
    *_specs("admin/camera_security", "camera_security", ("set",), safety="mutation"),
    *_specs(
        "admin/camera_security",
        "camera_security_blocked_period",
        ("get",),
        sensitivity="private",
    ),
    *_specs(
        "admin/camera_security",
        "camera_security_blocked_period",
        ("set",),
        safety="mutation",
    ),
    *_specs("admin/firmware", "config", ("read", "check"), sensitivity="secret"),
    *_specs(
        "admin/firmware",
        "config",
        ("backup",),
        response_kind="binary",
        sensitivity="secret",
        media_type="application/octet-stream",
    ),
    *_specs("admin/firmware", "config", ("restore",), safety="destructive", sensitivity="secret"),
    *_specs(
        "admin/firmware",
        "config_multipart",
        ("upload",),
        authentication="multipart",
        response_kind="value",
        safety="destructive",
        sensitivity="secret",
    ),
    *_specs(
        "admin/firmware",
        "config_multipart",
        ("backup",),
        authentication="multipart",
        response_kind="binary",
        sensitivity="secret",
        media_type="application/octet-stream",
    ),
    *_specs(
        "admin/firmware",
        "config_multipart",
        ("restore",),
        authentication="multipart",
        response_kind="value",
        safety="destructive",
        sensitivity="secret",
    ),
    *_specs("admin/firmware", "upgrade", ("read",)),
    *_specs("admin/firmware", "upgrade", ("write",), safety="destructive"),
    *_specs("admin/isp", "isp_upgrade", ("read",)),
    *_specs(
        "admin/isp",
        "isp_upgrade",
        ("upgrade",),
        authentication="multipart",
        response_kind="value",
        safety="destructive",
    ),
    *_specs("mcu_upgrade", "mcu_upgrade", ("check",), safety="destructive"),
    *_specs("admin/cloud", "nickname", ("read",), sensitivity="private"),
    *_specs("admin/cloud", "nickname", ("write",), safety="mutation"),
    *_specs(
        "admin/cloud",
        "firmware",
        ("check", "status", "firmware_status", "sync_check_firmware", "get_sync"),
        authentication="plain",
    ),
    *_specs(
        "admin/cloud",
        "firmware",
        ("upgrade", "download", "local_upgrade"),
        authentication="plain",
        safety="destructive",
    ),
    *_specs(
        "admin/cloud",
        "firmware",
        ("auto_upgrade",),
        authentication="plain",
        safety="mutation",
    ),
    *_specs(
        "admin/cloud",
        "firmware",
        ("upload",),
        authentication="multipart",
        response_kind="value",
        safety="destructive",
        sensitivity="secret",
    ),
    *_specs("admin/cloud", "firmware_status", ("read", "check", "check_upgrade")),
    *_specs(
        "admin/cloud",
        "firmware_status",
        ("upgrade", "local_upgrade"),
        safety="destructive",
    ),
    *_specs("admin/cloud", "group", ("get",), sensitivity="secret"),
    *_specs("admin/cloud", "group", ("iot_read",), sensitivity="secret"),
    *_specs(
        "admin/cloud",
        "group",
        (
            "create",
            "add",
            "set",
            "update",
            "remove",
            "report",
            "message",
            "push",
            "push_weekly",
        ),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/cloud",
        "system",
        ("bind", "unbind", "remove_all", "transfer"),
        safety="destructive",
        sensitivity="secret",
    ),
    *_specs(
        "admin/cloud",
        "system",
        ("proxy", "account"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/cloud",
        "system",
        ("notify", "sync"),
        safety="internal",
        sensitivity="secret",
    ),
    *_specs("admin/cloud", "ddns", ("get",), sensitivity="secret"),
    *_specs("admin/cloud", "ddns", ("set",), safety="mutation", sensitivity="secret"),
    *_specs("admin/cloud", "manager", ("get",), sensitivity="secret"),
    *_specs("admin/cloud", "manager", ("set",), safety="mutation", sensitivity="secret"),
    *_specs("admin/cloud", "homecare_service", ("get",), sensitivity="private"),
    *_specs("admin/cloud_account", "read", ("read_keys",), sensitivity="secret"),
    *_specs(
        "admin/cloud_account",
        "read",
        ("get_device_token", "get_deviceInfo"),
        sensitivity="secret",
    ),
    *_specs(
        "admin/cloud_account",
        "login",
        ("user_login", "bind_and_login", "cloud_bind_and_login"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/cloud_account", "check_internet", ("read",)),
    *_specs("admin/cloud_account", "check_device", ("read",)),
    *_specs("admin/cloud_account", "check_connection", ("read",)),
    *_specs("admin/cloud_account", "check_login", ("read",), sensitivity="secret"),
    *_specs("admin/cloud_account", "check_cloud_connection", ("read",)),
    *_specs("admin/cloud_account", "check_support", ("read",)),
    *_specs("admin/cloud_account", "bind_owner", ("write",), safety="destructive"),
    *_specs("admin/cloud_account", "unbind_owner", ("write",), safety="destructive"),
    *_specs("admin/cloud_account", "get_dev_info", ("read",), sensitivity="private"),
    *_specs(
        "admin/cloud_account",
        "get_deviceInfo",
        ("read",),
        sensitivity="private",
    ),
    *_specs("admin/cloud_account", "set_dev_info", ("write",), safety="mutation"),
    *_specs(
        "admin/cloud_account",
        "cloud_pass_through",
        ("write",),
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/cloud_account",
        "tmp_cloud_pass_through",
        ("write",),
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/cloud_account",
        "upgrade",
        ("write",),
        safety="destructive",
        sensitivity="secret",
    ),
    *_specs(
        "admin/cloud_account",
        "cloud_upgrade",
        ("write",),
        safety="destructive",
        sensitivity="secret",
    ),
    *_specs("admin/cloud_account", "load", ("read",), sensitivity="secret"),
    *_specs("admin/cloud_account", "get_token", ("read",), sensitivity="secret"),
    *_specs(
        "admin/cloud_account",
        "tmp_cmd",
        ("write",),
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/cloud_account",
        "write",
        ("write",),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/iot_device",
        "iotdevice",
        ("getlist", "getlist_by_mod"),
        sensitivity="private",
    ),
    *_specs(
        "admin/iot_device",
        "iotdevice",
        (
            "add",
            "modify",
            "remove",
            "scan",
            "begin_scan",
            "end_scan",
            "identify",
        ),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/iot_device",
        "iotdevice",
        ("account_sync",),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/iot_device",
        "iotdevice",
        (
            "inner_getlist",
            "inner_remove",
            "inner_modify",
            "inner_scan",
            "inner_begin_scan",
            "inner_inquiry",
            "inner_begin_assoc",
            "inner_get",
            "inner_act",
            "inner_act_qr",
            "inner_upnp_get",
            "inner_dhcpd_get",
            "inner_file_pull",
            "inner_file_push",
            "inner_client_mgmt",
            "inner_client_netdev_req",
        ),
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/iot_device",
        "iotprofile",
        ("get_and_update_pwd",),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/iot_device",
        "iotspace",
        ("set", "set_network_device", "remove_network_device"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/iot_device", "iotowner", ("get", "getlist"), sensitivity="private"),
    *_specs(
        "admin/iot_device",
        "iotowner",
        ("set",),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/iot_device",
        "iotowner",
        ("testcmd", "inner_report_sensor", "inner_network", "form_network"),
        safety="internal",
        sensitivity="private",
    ),
    *_specs(
        "admin/iot_device",
        "iotowner",
        ("remove_all",),
        safety="destructive",
        sensitivity="private",
    ),
    *_specs(
        "admin/iot_device",
        "iotrole",
        ("get_init_info", "get_avail_node_id", "check_node_status"),
        sensitivity="private",
    ),
    *_specs(
        "admin/iot_device",
        "iotrole",
        ("commission_complete", "get_pairing_code"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/iot_device",
        "iotrole",
        ("inner_update_config",),
        safety="internal",
        sensitivity="secret",
    ),
    *_specs("admin/iot_automation", "iotautomation", ("get_tasklist",), sensitivity="private"),
    *_specs(
        "admin/iot_automation",
        "iotautomation",
        (
            "add_task",
            "modify_task",
            "modify_task_list",
            "remove_tasklist",
            "add_trigger",
            "modify_trigger",
            "remove_triggerlist",
        ),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs(
        "admin/iot_automation", "iotoneclick", ("getlist", "get_history"), sensitivity="private"
    ),
    *_specs(
        "admin/iot_automation",
        "iotoneclick",
        (
            "set",
            "add_scene",
            "modify_scene",
            "remove_scene",
            "add_action",
            "modify_action",
            "remove_actionlist",
            "remove_history",
        ),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/wps", "status", ("get",)),
    *_specs("admin/wps", "state", ("set",), safety="mutation", sensitivity="secret"),
    *_specs("admin/vpn_client", "config", ("read", "load"), sensitivity="secret"),
    *_specs(
        "admin/vpn_client",
        "config",
        ("write", "insert", "update", "remove"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/vpn_server", "server", ("read",), sensitivity="secret"),
    *_specs(
        "admin/vpn_server",
        "server",
        ("insert", "remove", "update"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/vpn_server",
        "accounts",
        ("insert", "remove", "update"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/vpn_server", "cert", ("get",), sensitivity="secret"),
    *_specs("admin/vpn_server", "cert", ("set",), safety="mutation", sensitivity="secret"),
    *_specs("admin/vpn_server", "key", ("gets", "getc"), sensitivity="secret"),
    *_specs(
        "admin/vpn_server",
        "key",
        ("renews", "renewc"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/vpnconn", "conn", ("list",), sensitivity="private"),
    *_specs("admin/vpnconn", "conn", ("disconnect",), safety="mutation"),
    *_specs("admin/vpnconn", "cert", ("sync",), safety="internal", sensitivity="secret"),
    *_specs("admin/nat", "setting", ("read",)),
    *_specs("admin/nat", "setting", ("write",), safety="mutation"),
    *_specs("admin/nat", "vs", ("getlist",), sensitivity="private"),
    *_specs(
        "admin/nat",
        "vs",
        ("add", "modify", "batch_remove", "remove"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/nat", "pt", ("load",), sensitivity="private"),
    *_specs("admin/nat", "pt", ("insert", "update"), safety="mutation"),
    *_specs("admin/nat", "dmz", ("read",), sensitivity="private"),
    *_specs("admin/nat", "dmz", ("write",), safety="mutation", sensitivity="private"),
    *_specs("admin/nat", "alg", ("get",)),
    *_specs("admin/nat", "alg", ("write",), safety="mutation"),
    *_specs("admin/nat", "sip_alg", ("get",)),
    *_specs("admin/nat", "sip_alg", ("set",), safety="mutation"),
    *_specs("admin/ddns", "ddns", ("get",), sensitivity="secret"),
    *_specs("admin/ddns", "ddns", ("set",), safety="mutation", sensitivity="secret"),
    *_specs("admin/ipv6_firewall", "firewall", ("read",), sensitivity="private"),
    *_specs(
        "admin/ipv6_firewall",
        "firewall",
        ("write", "remove", "modify"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/ipv6_firewall", "client", ("read",), sensitivity="private"),
    *_specs("admin/iptv", "iptv", ("get",)),
    *_specs("admin/iptv", "iptv", ("set",), safety="mutation"),
    *_specs("admin/usbshare", "device", ("list", "list_all"), sensitivity="private"),
    *_specs(
        "admin/usbshare",
        "device",
        ("scan", "remove", "remove_list"),
        safety="mutation",
        sensitivity="private",
    ),
    *_specs("admin/usbshare", "server", ("read", "read_list"), sensitivity="secret"),
    *_specs(
        "admin/usbshare",
        "server",
        ("write", "write_list"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/usbshare", "status", ("read",)),
    *_specs("admin/usbshare", "sync", ("read",), safety="internal"),
    *_specs("admin/time_machine", "settings", ("read",), sensitivity="secret"),
    *_specs("admin/time_machine", "settings", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/time_machine", "info", ("read",), sensitivity="private"),
    *_specs("admin/time_machine", "content", ("read",), sensitivity="private"),
    *_specs(
        "admin/administration",
        "account",
        ("read", "appget", "mcu_read", "mcu_check"),
        sensitivity="secret",
    ),
    *_specs(
        "admin/administration",
        "account",
        ("write", "set", "appset", "mcu_write"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/administration", "recovery", ("read",), sensitivity="secret"),
    *_specs(
        "admin/administration", "recovery", ("update",), safety="destructive", sensitivity="secret"
    ),
    *_specs("admin/administration", "mode", ("local", "remote"), safety="mutation"),
    *_specs("admin/administration", "local", ("load", "view"), sensitivity="secret"),
    *_specs(
        "admin/administration",
        "local",
        ("insert", "update", "remove"),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs("admin/administration", "remote", ("read",), sensitivity="secret"),
    *_specs("admin/administration", "remote", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/administration", "login", ("read",), sensitivity="secret"),
    *_specs("admin/administration", "login", ("write",), safety="mutation", sensitivity="secret"),
    *_specs(
        "discover",
        "_discover",
        ("read",),
        authentication="group_key",
        safety="internal",
        sensitivity="private",
    ),
    *_specs(
        "discover",
        "sync_config",
        ("read",),
        authentication="group_key",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "discover",
        "sync_config_emmc",
        ("read",),
        authentication="group_key",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "discover",
        "sync_slave_check",
        ("read",),
        authentication="group_key",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "discover",
        "sync_master_check",
        ("read",),
        authentication="group_key",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs("admin/log", "log", ("read", "load"), sensitivity="secret"),
    *_specs("admin/log", "log", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/log_export", "types", ("read",), response_kind="list"),
    *_specs("admin/log_export", "save", ("write",), safety="mutation", sensitivity="secret"),
    *_specs(
        "admin/log_export",
        "save_log",
        ("download",),
        authentication="download",
        response_kind="binary",
        sensitivity="secret",
        media_type="text/plain",
    ),
    *_specs(
        "admin/log_export", "feedback_log", ("build",), safety="mutation", sensitivity="secret"
    ),
    *_specs("admin/log_export", "feedback_log", ("read",), sensitivity="secret"),
    *_specs("admin/syslog", "mail", ("read",), sensitivity="secret"),
    *_specs("admin/syslog", "mail", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/syslog", "log", ("mail",), safety="mutation", sensitivity="secret"),
    *_specs("admin/telemetry_collect", "telemetry_device", ("read",), sensitivity="private"),
    *_specs("admin/telemetry_collect", "telemetry_client", ("read",), sensitivity="private"),
    *_specs("admin/telemetry_collect", "telemetry_system", ("read",), sensitivity="private"),
    *_specs("admin/telemetry_collect", "telemetry_usb", ("read",), sensitivity="private"),
    *_specs("admin/telemetry_collect", "telemetry_control", ("read",)),
    *_specs("admin/telemetry_collect", "telemetry_control", ("write",), safety="mutation"),
    *_specs("admin/debug", "qlog", ("start", "stop"), safety="internal", sensitivity="secret"),
    *_specs("admin/debug", "simplecom", ("start", "stop"), safety="internal", sensitivity="secret"),
    *_specs("admin/debug", "tty2tcp", ("start", "stop"), safety="internal", sensitivity="secret"),
    *_specs("admin/debug", "tm", ("start", "stop"), safety="internal", sensitivity="secret"),
    *_specs("admin/auto_test", "test", ("nat", "upnp", "dhcp", "wifi"), safety="internal"),
    *_specs("admin/auto_test", "test", ("all_info",), safety="internal", sensitivity="secret"),
    *_specs("admin/arptbl", "syn", ("tbl_op",), safety="internal", sensitivity="private"),
    *_specs("admin/cwmp", "cwmp", ("get",), sensitivity="secret"),
    *_specs("admin/cwmp", "cwmp", ("set",), safety="mutation", sensitivity="secret"),
    *_specs("admin/cwmp", "cwmp_info", ("read",), sensitivity="secret"),
    *_specs("admin/cwmp", "cwmp_info", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/folder_sharing", "tree", ("read",), sensitivity="private"),
    *_specs("admin/combo_port", "list", ("read",)),
    *_specs("admin/combo_port", "switch", ("set",), safety="mutation"),
    *_specs("admin/component_list", "mobile", ("read",)),
    *_specs("admin/component_list", "bluetooth", ("read",)),
    *_specs("admin/component_list", "profile", ("read",)),
    *_specs("admin/ga_info", "status", ("read", "get", "get_internal"), sensitivity="private"),
    *_specs("admin/ga_info", "status", ("write",), safety="mutation"),
    *_specs("admin/op_manager", "read", ("get", "list", "getlist"), safety="internal"),
    *_specs("admin/wifidog", "portal_content", ("read",), sensitivity="secret"),
    *_specs(
        "admin/wifidog",
        "portal_content",
        ("upload",),
        safety="mutation",
        sensitivity="secret",
    ),
    *_specs(
        "admin/iot_cloud", "iot_cloud_req", ("index",), safety="internal", sensitivity="secret"
    ),
    *_specs(
        "admin/iot_client_mesh",
        "client_mesh",
        ("set", "tss", "sync_device_msg", "sync_cloud_msg"),
        safety="internal",
        sensitivity="private",
    ),
    *_specs("admin/msg_server", "coordinator", ("notify",), safety="internal"),
    *_specs("admin/msg_server", "notify", ("notify",), safety="internal"),
    *_specs("admin/wpsd", "main", ("report",), safety="internal", sensitivity="secret"),
    *_specs("admin/wpsd", "code", ("report",), safety="internal", sensitivity="secret"),
    *_specs(
        "admin/quick_setup", "newgroup", ("write",), safety="destructive", sensitivity="secret"
    ),
    *_specs(
        "admin/quick_setup", "newdevice", ("write",), safety="destructive", sensitivity="secret"
    ),
    *_specs(
        "admin/quick_setup", "batchdevices", ("write",), safety="destructive", sensitivity="secret"
    ),
    *_specs("admin/quick_setup", "preconf", ("read",), sensitivity="secret"),
    *_specs(
        "admin/quick_setup",
        "preconf",
        ("write", "add"),
        safety="destructive",
        sensitivity="secret",
    ),
    *_specs("admin/quick_setup", "heartbeat", ("read",), safety="internal"),
    *_specs("admin/quick_setup", "sync", ("write",), safety="internal", sensitivity="secret"),
    *_specs(
        "admin/quick_setup",
        "eponymous_detect",
        ("read",),
        safety="internal",
        sensitivity="private",
    ),
    *_specs(
        "admin/quick_setup",
        "bluetooth",
        ("write",),
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/quick_setup",
        "dcmp_pre_config",
        ("write",),
        safety="destructive",
        sensitivity="secret",
    ),
    *_specs(
        "admin/quick_setup",
        "tss",
        ("write",),
        safety="internal",
        sensitivity="private",
    ),
    *_specs(
        "admin/quick_setup",
        "sync_dev_list",
        ("write",),
        safety="internal",
        sensitivity="private",
    ),
    *_specs(
        "admin/quick_setup", "get_dev_list", ("read",), safety="internal", sensitivity="private"
    ),
    *_specs(
        "admin/tipc-controller", "newdevice", ("write",), safety="internal", sensitivity="secret"
    ),
    *_specs("admin/tipc-controller", "sync", ("write",), safety="internal", sensitivity="secret"),
    *_specs(
        "admin/sync",
        "sync_check",
        ("read",),
        authentication="token",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/sync",
        "sync_config",
        ("write",),
        authentication="token",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/sync",
        "sync_emmc_check",
        ("read",),
        authentication="token",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/sync",
        "sync_emmc_config",
        ("write",),
        authentication="token",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/sync",
        "sync_get_info",
        ("read",),
        authentication="token",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/sync",
        "sync_get_cfg",
        ("read",),
        authentication="token",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/sync",
        "sync_subconfig",
        ("write",),
        authentication="token",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/sync",
        "sync_update_dev_list",
        ("write",),
        authentication="token",
        safety="internal",
        sensitivity="private",
    ),
    *_specs(
        "admin/sync",
        "sync_detect_slave",
        ("read",),
        authentication="token",
        safety="internal",
        sensitivity="private",
    ),
    *_specs(
        "admin/sync",
        "check_firmware",
        ("read",),
        authentication="token",
        safety="internal",
    ),
    *_specs(
        "admin/sync",
        "sync_firmware",
        ("write",),
        authentication="token",
        safety="internal",
    ),
    *_specs(
        "admin/sync",
        "sync_upgrade",
        ("write",),
        authentication="token",
        safety="destructive",
    ),
    *_specs(
        "admin/sync",
        "force_upgrade",
        ("write",),
        authentication="token",
        safety="destructive",
    ),
    *_specs(
        "admin/sync",
        "sync_download_bigfirm",
        ("write",),
        authentication="token",
        safety="internal",
    ),
    *_specs(
        "admin/sync",
        "sync_download_status_bigfirm",
        ("read",),
        authentication="token",
        safety="internal",
    ),
    *_specs(
        "admin/sync",
        "sync_download_lte",
        ("write",),
        authentication="token",
        safety="internal",
    ),
    *_specs(
        "admin/sync",
        "sync_download_status_lte",
        ("read",),
        authentication="token",
        safety="internal",
    ),
    *_specs(
        "admin/sync",
        "force_upgrade_lte",
        ("write",),
        authentication="token",
        safety="destructive",
    ),
    *_specs(
        "admin/sync",
        "sync_isp_profile",
        ("write",),
        authentication="token",
        safety="internal",
        sensitivity="secret",
    ),
    *_specs(
        "admin/sync",
        "sync_re_handle_fap_fdb",
        ("write",),
        authentication="token",
        safety="internal",
        sensitivity="private",
    ),
    *_specs("blocking", "check", ("get",), sensitivity="private"),
    *_specs("blocking", "check", ("set",), safety="mutation", sensitivity="private"),
    *_specs("blocking", "vercode", ("read",), sensitivity="secret"),
    *_specs("blocking", "vercode", ("write",), safety="mutation", sensitivity="secret"),
    *_specs("admin/conn-indicator", "internet", ("down", "sync"), safety="internal"),
    *_specs("admin/re_disconnect_cloud", "notify", ("write",), safety="internal"),
)

_BY_NAME: dict[str, EndpointSpec] = {endpoint.name: endpoint for endpoint in ENDPOINT_CATALOG}

_CAPABILITY_NAMES: frozenset[str] = frozenset(
    {
        "admin.component_control.switch_list.read",
        "admin.web.extra_component_info.get",
        "admin.component_list.mobile.read",
        "admin.wireless.get_support.read",
    }
)

_P9_READ_NAMES: frozenset[str] = frozenset(
    {
        "admin.network.wan_mode.read",
        "admin.network.lan_ipv4.read",
        "admin.network.lan_ip.read",
        "admin.network.internet.read",
        "admin.network.vlan.read",
        "admin.network.mac_clone.read",
        "admin.network.performance.read",
        "admin.wireless.operation_mode.read",
        "admin.wireless.bridge.read",
        "admin.wireless.ieee80211r.read",
        "admin.wireless.beamforming.read",
        "admin.device.device_list.read",
        "admin.device.mode.read",
        "admin.device.speedtest.read",
        "admin.device.timesetting.read",
        "admin.component_control.switch_list.read",
        "locale.lang.read",
        "locale.country.read",
        "locale.country_list.read",
        "admin.client.client_list.read",
        "admin.client.traffic_stat.list",
        "admin.client.black_list.list",
        "admin.client.addr_reservation.getlist",
        "admin.cloud.nickname.read",
        "admin.cloud.firmware_status.read",
        "admin.cloud.firmware_status.check",
        "admin.cloud.firmware_status.check_upgrade",
        "admin.cloud_account.check_internet.read",
        "admin.cloud_account.check_device.read",
        "admin.cloud_account.check_connection.read",
        "admin.cloud_account.check_cloud_connection.read",
        "admin.cloud_account.check_support.read",
        "admin.cloud_account.get_dev_info.read",
        "admin.log_export.types.read",
        "login.auth.read",
        "login.keys.read",
        "login.check_factory_default.read",
    }
)

CAPABILITY_ENDPOINTS: tuple[EndpointSpec, ...] = tuple(
    endpoint for endpoint in ENDPOINT_CATALOG if endpoint.name in _CAPABILITY_NAMES
)
P9_READ_ENDPOINTS: tuple[EndpointSpec, ...] = tuple(
    endpoint for endpoint in ENDPOINT_CATALOG if endpoint.name in _P9_READ_NAMES
)
_P9_SUPPORTED_FORMS: frozenset[tuple[str, str]] = frozenset(
    (endpoint.path, endpoint.form) for endpoint in P9_READ_ENDPOINTS
)
P9_MUTATION_CANDIDATES: tuple[EndpointSpec, ...] = tuple(
    endpoint
    for endpoint in ENDPOINT_CATALOG
    if endpoint.safety != "read_only" and (endpoint.path, endpoint.form) in _P9_SUPPORTED_FORMS
)
READ_ONLY_ENDPOINTS: tuple[EndpointSpec, ...] = tuple(
    endpoint for endpoint in ENDPOINT_CATALOG if endpoint.safety == "read_only"
)
DISCOVERABLE_READ_ENDPOINTS: tuple[EndpointSpec, ...] = tuple(
    endpoint
    for endpoint in READ_ONLY_ENDPOINTS
    if endpoint.sensitivity != "secret"
    and (endpoint.generic_call_supported or endpoint.bootstrap_call_supported)
)
MUTATION_ENDPOINTS: tuple[EndpointSpec, ...] = tuple(
    endpoint for endpoint in ENDPOINT_CATALOG if endpoint.safety != "read_only"
)


def get_endpoint(name: str) -> EndpointSpec:
    """Return one documented operation by its stable dotted name."""
    try:
        return _BY_NAME[name]
    except KeyError as exc:
        raise KeyError(f"Unknown Deco endpoint operation: {name}") from exc
